version: '3.8'

services:
  whois-app:
    build: .
    container_name: whois-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
